# Usage:
#   conda build -c defaults -c conda-forge .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}
package:
  name: dask-cudf
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: py{{ py_version }}_{{ git_revision_count }}

requirements:
  host:
    - python x.x
    - cudf 0.7*
    - dask >=1.2.2
    - distributed >=1.23.0
  run:
    - python x.x
    - cudf 0.7*
    - dask >=1.2.2
    - distributed >=1.23.0
test:
  imports:
    - dask_cudf

about:
  home: http://rapids.ai
  license: Apache
  license_file: ../../../LICENSE.txt
  summary: dask-cudf library
